complaint_site/Controllers/ReportsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using complaint_site.Models;
using complaint_site.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Mvc;
using System.Web;

namespace complaint_site.Controllers
{
    [YourCustomAuthorize(Roles = "Admin, Worker, Customer")]
    public class ReportsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            if (User.IsInRole("Customer") == true)
            {
                var checkUserID = User.Identity.GetUserId();
                var data = db.Reports.Where(v => v.User.Id == checkUserID).ToList();
                return View(data);
            }
            else
            {
                return View(db.Reports.ToList());
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report data = db.Reports.Include("Images").Where(l => l.IdReport == id).FirstOrDefault();
            
            if (data == null)
            {
                return HttpNotFound();
            }
            return View(data);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdReport,Description,Type,Category,Data_of_issue,Status,ReplyReport,SinceWhen,OthershaveProblem,Devices,SpeedInternet,AllSites,SiteUrl,ProgramName,ReasonForComplaint,PlaceComplaint,DuplicateContract,Expectations")] Report report, HttpPostedFileBase postedFile)
        {
            var userManger = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            ApplicationUser currentUser = userManger.FindById(User.Identity.GetUserId());
            Customer customer = db.Customers.Where(c => c.User.Id == currentUser.Id).SingleOrDefault();
            string userEmail = User.Identity.GetUserName();
            report.Status = "Do rozpatrzenia";

            var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
            if (ModelState.IsValid)
            {
                if (postedFile != null)
                {
                    byte[] bytes;
                    using (BinaryReader br = new BinaryReader(postedFile.InputStream))
                    {
                        bytes = br.ReadBytes(postedFile.ContentLength);
                    }
                    Image img = new Image
                    {
                        Name = Path.GetFileName(postedFile.FileName),
                        ContentType = postedFile.ContentType,
                        Data = bytes,
                        IdReport = report.IdReport
                    };
                    db.Images.Add(img);
                }

                report.Customer = customer;
                report.User = currentUser;
                db.Reports.Add(report);
                db.SaveChanges();
                ViewBag.Added = "Sukces";

                ConfirmSendReportEmail email = new ConfirmSendReportEmail();
                email.To = userEmail;
                email.From = "develogic@h339.mikr.dev";
                email.IdReport = report.IdReport;
                email.Category = report.Category;
                email.Type = report.Type;
                email.Data_of_issue = report.Data_of_issue;
                email.Send();

                return RedirectToAction("Index");
            }

            return View(report);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            report.Description = "";
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdReport,Description,Type,Category,Data_of_issue,Status,ReplyReport,SinceWhen,OthershaveProblem,Devices,SpeedInternet,AllSites,SiteUrl,ProgramName,ReasonForComplaint,PlaceComplaint,DuplicateContract,Expectations")] Report report)
        {
            var errors = ModelState
           .Where(x => x.Value.Errors.Count > 0)
           .Select(x => new { x.Key, x.Value.Errors })
           .ToArray();
            if (ModelState.IsValid)
            {
                db.Entry(report).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(report);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Report report = db.Reports.Find(id);
            db.Reports.Remove(report);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ReplyReport(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var data = db.Reports.Where(d => d.IdReport == id).FirstOrDefault();
            var model = new ReportViewModel
            {
                IdReport = data.IdReport,
                Description = data.Description,
                Status = data.Status,
                ReplyReport = data.ReplyReport,
                Type = data.Type,
                Category = data.Category,
                Customer = data.Customer
            };
           
            if (id == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReplyReport(ReportViewModel report, 
            string success, string needSomeInfo, string failed, string begin)
        {
            if (success != null)
            {
                report.Status = "Rozpatrzono";
            }
            else if (needSomeInfo != null)
            {
                report.Status = "Wymaga dodatkowych informacji";
            }
            else if (failed != null)
            {
                report.Status = "Odrzucono";
            }
            else if (begin != null)
            {
                report.Status = "W trakcie realizacji";
            }
            var userManger = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            ApplicationUser currentUser = userManger.FindById(User.Identity.GetUserId());
            Worker worker = db.Workers.Where(c => c.User.Id == currentUser.Id).SingleOrDefault();
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {

                var data = db.Reports.Where(x => x.IdReport == report.IdReport).SingleOrDefault();
                Customer customer = db.Customers.Where(h => 
                h.IdCustomer == data.Customer.IdCustomer).SingleOrDefault();
                string userEmail = customer.User.Email;
                data.DataChangeStatus = DateTime.Now;
                data.Status = report.Status;
                data.ReplyReport = report.ReplyReport;
                data.Workers = worker;
                db.SaveChanges();
                AnswerForReportEmail email = new AnswerForReportEmail();
                email.To = userEmail;
                email.From = "develogic@h339.mikr.dev";
                email.Status = report.Status;
                email.ReplyReport = report.ReplyReport;
                email.Send();
                return RedirectToAction("Index");
            }
            return View(report);
        }

        public ActionResult AddAnswer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var data = db.Reports.Where(d => d.IdReport == id).FirstOrDefault();
            var model = new ReportViewModel
            {
                IdReport = data.IdReport,
                Description = "",
                ReplyReport = data.ReplyReport,
            };
            if (id == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAnswer(ReportViewModel report)
        {
            report.Status = "Do rozpatrzenia";
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                var data = db.Reports.Where(x => x.IdReport == report.IdReport).SingleOrDefault();
                Customer customer = db.Customers.Where(h => h.IdCustomer == data.Customer.IdCustomer).SingleOrDefault();
                string userEmail = customer.User.Email;
                data.Data_of_issue = DateTime.Now;
                data.Status = "Do rozpatrzenia";
                data.ReplyReport = "";
                data.Description = report.Description;
                db.SaveChanges();
                

complaint_site/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using complaint_site.Models;
using complaint_site.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace complaint_site.Controllers
{
    [YourCustomAuthorize(Roles = "Admin")]
    public class WorkersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));

        public ActionResult Index()
        {
            var data = db.Workers.ToList();
            var returnmodel = data.Select(item => new WorkerViewModel
            {
                IdWorker = item.IdWorker,
                Name = item.Name,
                Surname = item.Surname,
                City = item.City,
                Street = item.Street,
                HouseNumber = item.HouseNumber,
                ZIPCode = item.ZIPCode,
                WorkPhone = item.WorkPhone
            }
            );
            return View(returnmodel);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(WorkerViewModel worker)
        {
            Worker NewWorker = new Worker
            {
                Name = worker.Name,
                Surname = worker.Surname,
                PrivatePhone = worker.PrivatePhone,
                WorkPhone = worker.WorkPhone,
                City = worker.City,
                Street = worker.Street,
                HouseNumber = worker.HouseNumber,
                ZIPCode = worker.ZIPCode,
                Pesel = worker.Pesel,
                IdNumber = worker.IdNumber
            };

            if (ModelState.IsValid)
            {
                var getUserName = NewWorker.Name[0] + NewWorker.Surname + "@isp.com";
                var getPasswordName = NewWorker.Surname + "." + NewWorker.Pesel[7] + NewWorker.Pesel[8] 
                    + NewWorker.Pesel[9] + NewWorker.Pesel[10];
                getUserName = getUserName.Replace('Ą', 'A').Replace('ą', 'a')
                    .Replace('Ć', 'C').Replace('ć', 'c')
                    .Replace('Ę', 'E').Replace('ę', 'e')
                    .Replace('Ł', 'L').Replace('ł', 'l')
                    .Replace('Ń', 'N').Replace('ń', 'n')
                    .Replace('Ó', 'O').Replace('ó', 'o')
                    .Replace('Ś', 'S').Replace('ś', 's')
                    .Replace('Ź', 'Z').Replace('ź', 'z')
                    .Replace('Ż', 'Z').Replace('ż', 'z');
                getPasswordName = getPasswordName.Replace('Ą', 'A').Replace('ą', 'a')
                    .Replace('Ć', 'C').Replace('ć', 'c')
                    .Replace('Ę', 'E').Replace('ę', 'e')
                    .Replace('Ł', 'L').Replace('ł', 'l')
                    .Replace('Ń', 'N').Replace('ń', 'n')
                    .Replace('Ó', 'O').Replace('ó', 'o')
                    .Replace('Ś', 'S').Replace('ś', 's')
                    .Replace('Ź', 'Z').Replace('ź', 'z')
                    .Replace('Ż', 'Z').Replace('ż', 'z');

                var user = new ApplicationUser { UserName = getUserName, Email = getUserName };
                var result = await userManager.CreateAsync(user, getPasswordName);
                if (result.Succeeded)
                {
                    db.Workers.Add(NewWorker);
                    userManager.AddToRole(user.Id, "Worker");
                }             
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Worker worker = db.Workers.Find(id);
                if (worker == null)
                {
                    return HttpNotFound();
                }
                return View(worker);
            }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdWorker,Name,Surname,PrivatePhone,WorkPhone,City,Street,ZIPCode,HouseNumber,Pesel,IdNumber")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(worker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(worker);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Worker worker = db.Workers.Find(id);
            db.Workers.Remove(worker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

complaint_site/Views/Shared/ManageNav.cshtml
@using Microsoft.AspNet.Identity
    <section class="manageNav">
        @if (Context.User.IsInRole("Customer"))
        {
            <ul class="nav nav-tabs justify-content-center">
                <li class="nav-item ">
                    <a class="nav-link" id="mojeKonto" href="@Url.Action("Index", "Manage")">Moje konto</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Reports")" class="nav-link" id="zgloszenia">Zgłoszenia</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("PersonalData", "Manage")" id="mojeDane">Moje dane</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ChangePassword", "Manage")" id="zmianaHasla">Zmiana hasła</a>
                </li>
                <li class="nav-item text-right">
                    <a class="btn btn-primary ml-2" href="javascript:document.getElementById('logoutForm').submit()" id="zmianaHasla">Wyloguj się</a>
                </li>
            </ul>
        }
        @if (Context.User.IsInRole("Worker"))
        {
            <ul class="nav nav-tabs justify-content-center">
                <li class="nav-item ">
                    <a class="nav-link" id="mojeKonto" href="@Url.Action("Index", "Manage")">Moje konto</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Reports")" class="nav-link" id="zgloszenia">Zgłoszenia klientów</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Customers")" id="klienci">Klienci</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ChangePassword", "Manage")" id="zmianaHasla">Zmiana hasła</a>
                </li>
                <li class="nav-item text-right">
                    <a class="btn btn-secondary" href="javascript:document.getElementById('logoutForm').submit()" id="zmianaHasla">Wyloguj się</a>
                </li>
            </ul>
        }
        @if (Context.User.IsInRole("Admin"))
        {
    <ul class="nav nav-tabs justify-content-center">
        <li class="nav-item ">
            <a class="nav-link" id="mojeKonto" href="@Url.Action("Index", "Manage")">Moje konto</a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("Index", "Reports")" class="nav-link" id="zgloszenia">Zgłoszenia klientów</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Customers")" id="klienci">Klienci</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Workers")" id="pracownicy">Pracownicy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("ChangePassword", "Manage")" id="zmianaHasla">Zmiana hasła</a>
        </li>
        <li class="nav-item text-right">
            <a class="btn btn-warning" href="javascript:document.getElementById('logoutForm').submit()" id="zmianaHasla">Wyloguj się</a>
        </li>
    </ul>
        }
    </section>
<div class="separatorNav"></div>

complaint_site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/fontello-303355d3/css/fontello.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/zoom.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="d-flex flex-column">
    <nav class="navbar navbar-expand-lg navbar-dark bg-black text-uppercase sticky-top">
        <div class="container px-3">
            <a class="ispLogo link-green" href="@Url.Action("Index", "Home")">ISP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center mx-auto" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item py-1 px-3">
                        <a class="link-green " href="@Url.Action("Index", "Home")">Strona główna</a>
                    </li>
                    <li class="nav-item py-1 px-3">
                        <a href="" id="offer" class="link-green">oferta</a>
                    </li>

                    <li class="nav-item py-1 px-3">
                        <a class="link-green" href="@Url.Action("Regulations", "Home")">Regulamin</a>
                    </li>
                    <li class="nav-item py-1 px-3">
                        <a class="link-green" href="@Url.Action("Contact", "Home")">Kontakt</a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <main role="main">
        <div class="container body-content">
            @RenderBody()
        </div>
    </main>
    <footer class="mt-auto py-3">
        <div class="">
            <p>Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie</p>
            <p>&copy; @DateTime.Now.Year</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.bootstrap4.min.js"></script>
    <script>
        if (typeof login !== 'undefined') {
            document.querySelector("main .container").classList.remove("container");
        }
        else if (typeof register !== 'undefined') {
            document.querySelector("main .container").classList.remove("container");
        }

        if (typeof home !== 'undefined') {
            document.querySelector("main .container").classList.add("margin-0");
            document.querySelector("nav").classList.remove("sticky-top");
            document.querySelector("nav").classList.add("fixed-top");
            document.querySelector("nav").classList.add("homeNavbar");
            document.querySelector("#offer").href = "#tariffs";
        }
        else {
            document.querySelector("#offer").href = '@Url.Action("Index", "Home")#tariffs';
        }

        //backgrounds
        if (typeof contact !== 'undefined') {
            document.querySelector("main").classList.add("contactBackground");
        }
        if (typeof detailsReportWorker !== 'undefined') {
            document.querySelector("main").classList.add("detailsReportWorker");
        }

        $(document).ready(function () {
            $("#customerTable").DataTable({
                language: {
                    search: "Szukaj",
                    processing: "Wczytywanie danych",
                    lengthMenu: "Pokaż _MENU_  elementów",
                    info: "Wyświetlono od _START_ do _END_ z _TOTAL_ elementów",
                    infoEmpty:      "Wyświetlono od 0 do 0 z 0 elementów",
                    infoFiltered:   "( _MAX_ )",
                    infoPostFix:    "",
                    loadingRecords: "Wczytywanie danych...",
                    zeroRecords:    "Brak danych",
                    emptyTable:     "Baza pracowników jest pusta",
                    paginate: {
                       first:      "<<",
                       previous:   "<",
                       next:       ">",
                       last:       ">>"
                    },
                    aria: {
                        sortAscending: "Sortuj rosnąco",
                        sortDescending: "Sortuj malejąco"
                    }
                },
            });
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
            
        });

        $(document).ready(function () {
            $("#reportsTable").DataTable({
                "order": [[4, "asc"]],
                language: {
                    search: "Szukaj",
                    processing: "Wczytywanie danych",
                    lengthMenu: "Pokaż _MENU_  elementów",
                    info: "Wyświetlono od _START_ do _END_ z _TOTAL_ elementów",
                    infoEmpty:      "Wyświetlono od 0 do 0 z 0 elementów",
                    infoFiltered:   "( _MAX_ )",
                    infoPostFix:    "",
                    loadingRecords: "Wczytywanie danych...",
                    zeroRecords:    "Brak danych",
                    emptyTable:     "Baza zgłoszeń jest pusta",
                    paginate: {
                       first:      "<<",
                       previous:   "<",
                       next:       ">",
                       last:       ">>"
                    },
                    aria: {
                        sortAscending: "Sortuj rosnąco",
                        sortDescending: "Sortuj malejąco"
                    }

                },
            });
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });

        if (typeof checkBox != 'undefined') {
            var City = document.querySelector("#City");
    var Street = document.querySelector("#Street");
    var HouseNumber = document.querySelector("#HouseNumber");
    var ZIPCode = document.querySelector("#ZIPCode");
    var CityCorespondence = document.querySelector("#CityCorespondence");
    var StreetCorespondence = document.querySelector("#StreetCorespondence");
    var HouseNumberCorespondence = document.querySelector("#HouseNumberCorespondence");
    var ZIPCodeCorespondence = document.querySelector("#ZIPCodeCorespondence");

    checkBox.addEventListener('change', function (event) {
        if (this.checked) {
            CityCorespondence.value = City.value;
            CityCorespondence.readOnly = true;
            StreetCorespondence.value = Street.value;
            StreetCorespondence.readOnly = true;
            HouseNumberCorespondence.value = HouseNumber.value;
            HouseNumberCorespondence.readOnly = true;
            ZIPCodeCorespondence.value = ZIPCode.value;
            ZIPCodeCorespondence.readOnly = true;
        }
        else {
            CityCorespondence.readOnly = false;
            CityCorespondence.value = null;
            StreetCorespondence.readOnly = false;
            StreetCorespondence.value = "";
            HouseNumberCorespondence.readOnly = false;
            HouseNumberCorespondence.value = "";
            ZIPCodeCorespondence.readOnly = false;
            ZIPCodeCorespondence.value = "";
        }
    });
        }

         $(document).ready(function () {
        $('textarea').on("focus input", function () {
            $(this).css('height', 'auto').css('height', this.scrollHeight + (this.offsetHeight - this.clientHeight));
        });
    });

    </script>
</body>
</html>