complaint_site/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace complaint_site.Models
{
    public class Customer
    {
        [Key]
        public int IdCustomer { get; set; }
        [Required]
        [Display(Name = "Imię")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Imię zawiera tylko znaki od 'a' do 'z'")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Nazwisko")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[-a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Nazwisko zawiera tylko zanki od 'a' do 'z' i '-'")]
        public string Surname { get; set; }
        [Required]
        [Display(Name = "Miasto")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[-a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Nazwa miejscowości zawiera tylko litery i '-' ")]
        public string City { get; set; }
        [Required]
        [Display(Name = "Ulica")]
        [StringLength(50, MinimumLength = 2)]
        public string Street { get; set; }
        [Required]
        [Display(Name = "Numer budynku/mieszkania")]
        [StringLength(10)]
        public string HouseNumber { get; set; }
        [Required]
        [Display(Name = "Kod pocztowy")]
        [StringLength(6, MinimumLength = 6)]
        [RegularExpression(@"^\d{2}(-\d{3})?$", ErrorMessage = "Format kodu poczotwego to: 00-000")]
        public string ZIPCode { get; set; }
        [Display(Name = "Miejscowość")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[-a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Nazwa miejscowości zawiera tylko litery i '-' ")]
        public string CityCorespondence { get; set; }
        [Display(Name = "Ulica")]
        [StringLength(50, MinimumLength = 2)]
        public string StreetCorespondence { get; set; }
        [Display(Name = "Numer budynku/mieszkania")]
        [StringLength(10)]
        public string HouseNumberCorespondence { get; set; }
        [Display(Name = "Kod pocztowy")]
        [StringLength(6, MinimumLength = 6)]
        [RegularExpression(@"^\d{2}(-\d{3})?$", ErrorMessage = "Format kodu poczotwego to: 00-000")]
        public string ZIPCodeCorespondence { get; set; }
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Pesel zawiera 11 cyfr")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Pesel zawiera tylko cyfry")]
        public string Pesel { get; set; }
        [Required]
        [Display(Name = "Numer dowodu osobistego")]
        [StringLength(9, MinimumLength = 9)]
        [RegularExpression(@"^[a-zA-Z]{3}[0-9]{6}?$", ErrorMessage = "Format numeru dowodu osobistego to: XYZ123456")]
        public string IdNumber { get; set; }
        [Required]
        [Display(Name = "Telefon")]
        [StringLength(12, MinimumLength = 12)]
        [RegularExpression("^[+]{1}[0-9]{11}?$", ErrorMessage = "Wpisz numer w formacie: +48XXXXXXXXX")]
        public string Phone { get; set; }
        public int IdTariff { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}

complaint_site/ViewModels/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace complaint_site.ViewModels
{
    public class CustomerViewModel
    {
        public int IdCustomer { get; set; }
        [Required]
        [Display(Name = "Imię")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Imię zawiera tylko znaki od 'a' do 'z'")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Nazwisko")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[-a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Nazwisko zawiera tylko zanki od 'a' do 'z' i '-'")]
        public string Surname { get; set; }
        [Required]
        [Display(Name = "Miasto")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[-a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Nazwa miejscowości zawiera tylko litery i '-' ")]
        public string City { get; set; }
        [Required]
        [Display(Name = "Ulica")]
        [StringLength(50, MinimumLength = 2)]
        public string Street { get; set; }
        [Required]
        [Display(Name = "Numer budynku/mieszkania")]
        [StringLength(10)]
        public string HouseNumber { get; set; }
        [Required]
        [Display(Name = "Kod pocztowy")]
        [StringLength(6, MinimumLength = 6)]
        [RegularExpression(@"^\d{2}(-\d{3})?$", ErrorMessage = "Format kodu poczotwego to: 00-000")]
        public string ZIPCode { get; set; }
        [Display(Name = "Miejscowość")]
        [StringLength(50, MinimumLength = 2)]
        [RegularExpression("^[-a-zA-ZzżźćńółęąśŻŹĆĄŚĘŁÓŃ]*$", ErrorMessage = "Nazwa miejscowości zawiera tylko litery i '-' ")]
        public string CityCorespondence { get; set; }
        [Display(Name = "Ulica")]
        [StringLength(50, MinimumLength = 2)]
        public string StreetCorespondence { get; set; }
        [Display(Name = "Numer budynku/mieszkania")]
        [StringLength(10)]
        public string HouseNumberCorespondence { get; set; }
        [Display(Name = "Kod pocztowy")]
        [StringLength(6, MinimumLength = 6)]
        [RegularExpression(@"^\d{2}(-\d{3})?$", ErrorMessage = "Format kodu poczotwego to: 00-000")]
        public string ZIPCodeCorespondence { get; set; }
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Pesel zawiera 11 cyfr")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Pesel zawiera tylko cyfry")]
        public string Pesel { get; set; }
        [Required]
        [Display(Name = "Numer dowodu osobistego")]
        [StringLength(9, MinimumLength = 9)]
        [RegularExpression(@"^[a-zA-Z]{3}[0-9]{6}?$", ErrorMessage = "Format numeru dowodu osobistego to: XYZ123456")]
        public string IdNumber { get; set; }
        [Required]
        [Display(Name = "Telefon")]
        [StringLength(12, MinimumLength = 12)]
        [RegularExpression("^[+]{1}[0-9]{11}?$", ErrorMessage = "Wpisz numer w formacie: +48XXXXXXXXX")]
        public string Phone { get; set; }

        public int IdTariff { get; set; }
    }
}

complaint_site/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using complaint_site.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace complaint_site.Controllers
{
    [YourCustomAuthorize(Roles = "Admin, Worker")]
    public class CustomersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));

        [Authorize(Roles = "Admin, Worker")]

        public ActionResult Index()
        {
            var customers = db.Customers.Include(c => c.Tariff);
            return View(customers.ToList());

        }

        [Authorize(Roles = "Admin, Worker")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Worker")]
        public ActionResult LockUnlockAccountChnage(string locked, string unlocked)
        {
            if (locked != null)
            {
                Customer customer = db.Customers.Where(w => w.User.Id == locked).FirstOrDefault();
                DateTime dateLockAccount = new DateTime(2100, 1, 1);
                customer.User.LockoutEndDateUtc = dateLockAccount;
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Modal = "RUN!";
                return View("Details", customer);
            }
            else if (unlocked != null)
            {
                Customer customer = db.Customers.Where(w => w.User.Id == unlocked).FirstOrDefault();
                customer.User.LockoutEndDateUtc = null;
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Modal = "RUN!";
                return View("Details", customer);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            ViewBag.IdTariff = new SelectList(db.Tariffs, "IdTariff", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCustomer,Name,Surname,City,Street,HouseNumber,ZIPCode,CityCorespondence,StreetCorespondence,HouseNumberCorespondence,ZIPCodeCorespondence,Pesel,IdNumber,Phone,IdTariff")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdTariff = new SelectList(db.Tariffs, "IdTariff", "Name", customer.IdTariff);
            return View(customer);
        }

        [Authorize(Roles = "Admin, Worker")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);

            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdTariff = new SelectList(db.Tariffs, "IdTariff", "Name", customer.IdTariff);
            return View(customer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCustomer,Name,Surname,City,Street,HouseNumber,ZIPCode,CityCorespondence,StreetCorespondence,HouseNumberCorespondence,ZIPCodeCorespondence,Pesel,IdNumber,Phone,IdTariff")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdTariff = new SelectList(db.Tariffs, "IdTariff", "Name", customer.IdTariff);
            return View(customer);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
    public class YourCustomAuthorize : AuthorizeAttribute
    {
        public override void OnAuthorization(AuthorizationContext filterContext)
        {
            if (this.AuthorizeCore(filterContext.HttpContext))
            {
                base.OnAuthorization(filterContext);
            }
            else
            {
                filterContext.Result = new RedirectResult("/Home/Unauthorized");
            }
        }
    }
}

complaint_site/Views/Customers/Create.cshtml
@model complaint_site.Models.Customer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <section class="my-4 font-weight-bold">
        <h2 class="text-center">Nowy klient</h2>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <h4>Dane podstawowe:</h4>
            <div class="row">
                <div class="col-4 mx-auto">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Pesel, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.Pesel, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Pesel, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.IdNumber, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.IdNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.IdNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-4 mx-auto"></div>
            </div>
            <h4 class="mt-4">Adres główny:</h4>
            <div class="row">
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.HouseNumber, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.HouseNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HouseNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ZIPCode, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.ZIPCode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ZIPCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <h4 class="mt-4">Adres do korespondencji:</h4>
            <p class="font-weight-bolder">
                <input type="checkbox" value="thisSame" id="thisSame" />
                <label class="form-check-label" for="thisSame">Taki sam jak adres główny</label>
            </p>
            <div class="row">
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.CityCorespondence, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.CityCorespondence, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CityCorespondence, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.HouseNumberCorespondence, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.HouseNumberCorespondence, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HouseNumberCorespondence, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.StreetCorespondence, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.StreetCorespondence, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StreetCorespondence, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-4 mx-auto">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ZIPCodeCorespondence, htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class=" ">
                            @Html.EditorFor(model => model.ZIPCodeCorespondence, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ZIPCodeCorespondence, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <h4 class="mt-4">Wybór taryfy:</h4>
            <div class="row">
                <div class="form-group col-4 mx-auto">
                    <label class="control-label col-md-12">Taryfa</label>
                    <div class=" ">
                        @Html.DropDownList("IdTariff", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdTariff, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-4 mx-auto"></div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 text-center my-2">
                    <input type="submit" value="Dodaj" class="btn btn-outline-success font-weight-bold" />
                    <a href="@Url.Action("Index", "Customers")" class="btn btn-outline-primary font-weight-bold">Wróć do listy</a>
                </div>
            </div>
        }
    </section>

<script>
    var checkBox = document.querySelector("#thisSame");
</script>

complaint_site/Views/Customers/Delete.cshtml
@model complaint_site.Models.Customer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <section class="delete">
        <h4>Czy jesteś pewny na usunięcie klienta?</h4>
        <h3 class="text-danger mt-4">Jest to operacja nieodwracalna</h3>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions mt-5">
                <input type="submit" value="Tak chcę usunąć klienta" class="btn btn-danger font-weight-bold" />
                @Html.ActionLink("Wróć do klienta", "Details", new { id = Model.IdCustomer }, new { @class = "btn btn-dark font-weight-bold" })
                <a href="@Url.Action("Index", "Customers")" class="btn btn-primary font-weight-bold ">Wróć do listy</a>
            </div>
        }
    </section>

complaint_site/Views/Customers/Details.cshtml
@model complaint_site.Models.Customer
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("~/Views/Shared/ManageNav.cshtml")
<section class="mb-4">
    <h2 class="text-center">Dane klienta</h2>
    <hr />
    <div class="my-4">
        <a href="@Url.Action("Index", "Customers")" class="btn btn-outline-primary font-weight-bold">Wróć do listy</a>
    </div>
    <h4>Dane podstawowe:</h4>
    <div class="row">
        <div class="col-3 font-weight-bold text-right">
            <div>@Html.DisplayNameFor(model => model.Name)</div>
            <div>@Html.DisplayNameFor(model => model.Surname)</div>
            <div>@Html.DisplayNameFor(model => model.Phone)</div>
            <div>@Html.DisplayNameFor(model => model.Pesel)</div>
            <div>@Html.DisplayNameFor(model => model.IdNumber)</div>
        </div>
        <div class="col-3">
            <div>@Html.DisplayFor(model => model.Name)</div>
            <div>@Html.DisplayFor(model => model.Surname)</div>
            <div>@Html.DisplayFor(model => model.Phone)</div>
            <div>@Html.DisplayFor(model => model.Pesel)</div>
            <div>@Html.DisplayFor(model => model.IdNumber)</div>
        </div>
        <div class="col-2 font-weight-bold text-right">
            <div>@Html.DisplayNameFor(model => model.Tariff.Name)</div>
            <div>@Html.DisplayNameFor(model => model.Tariff.Parameters)</div>
            <div>@Html.DisplayNameFor(model => model.Tariff.Price)</div>
            <div>@Html.DisplayNameFor(model => model.User.Email)</div>
            <div class="mt-1">Status konta</div>
        </div>
        <div class="col-4">
            <div>@Html.DisplayFor(model => model.Tariff.Name)</div>
            <div>@Html.DisplayFor(model => model.Tariff.Parameters)</div>
            <div>@Html.DisplayFor(model => model.Tariff.Price) zł</div>
            <div>@Html.DisplayFor(model => model.User.UserName)</div>

            <div>
            @if (Model.User != null)
            {
                if (Model.User.LockoutEndDateUtc == null)
                {

                    if (User.IsInRole("Admin") || User.IsInRole("Worker"))
                    {
                        using (Html.BeginForm("LockUnlockAccountChnage", "Customers", FormMethod.Post))
                        {
                            <span class="badge badge-success">Konto aktywne</span>
                            <button type="submit" value="@Model.User.Id" name="locked" id="locked" class="btn btn-sm btn-danger lockUnlock">Zablokuj konto</button>
                        }
                    }
                }
                else
                {

                    if (User.IsInRole("Admin") || User.IsInRole("Worker"))
                    {
                        using (Html.BeginForm("LockUnlockAccountChnage", "Customers", FormMethod.Post))
                        {
                            <span class="badge badge-danger ">Konto zablokowane</span>
                            <button type="submit" value="@Model.User.Id" name="unlocked" id="unlocked" class="btn btn-sm btn-success lockUnlock">Odblokuj konto</button>
                        }
                    }
                }
            }
            else { 
                
                <div> </div>
                <div><span class="badge badge-info">Brak konta</span></div>
            }
            </div>
        </div>
    </div>
    <h4 class="mt-4">Adres główny:</h4>
    <div class="row">
        <div class="col-3 font-weight-bold text-right">
            <div>@Html.DisplayNameFor(model => model.City)</div>
            <div>@Html.DisplayNameFor(model => model.Street)</div>
            <div>@Html.DisplayNameFor(model => model.HouseNumber)</div>
            <div>@Html.DisplayNameFor(model => model.ZIPCode)</div>
        </div>
        <div class="col-4 ">
            <div>@Html.DisplayFor(model => model.City)</div>
            <div>@Html.DisplayFor(model => model.Street)</div>
            <div>@Html.DisplayFor(model => model.HouseNumber)</div>
            <div>@Html.DisplayFor(model => model.ZIPCode)</div>
        </div>
    </div>
    <h4 class="mt-4">Adres do korespondencji:</h4>
    <div class="row">
        <div class="col-3 font-weight-bold text-right">
            <div>@Html.DisplayNameFor(model => model.CityCorespondence)</div>
            <div>@Html.DisplayNameFor(model => model.StreetCorespondence)</div>
            <div>@Html.DisplayNameFor(model => model.HouseNumberCorespondence)</div>
            <div>@Html.DisplayNameFor(model => model.ZIPCodeCorespondence)</div>
        </div>
        <div class="col-4 ">
            <div>@Html.DisplayFor(model => model.CityCorespondence)</div>
            <div>@Html.DisplayFor(model => model.StreetCorespondence)</div>
            <div>@Html.DisplayFor(model => model.HouseNumberCorespondence)</div>
            <div>@Html.DisplayFor(model => model.ZIPCodeCorespondence)</div>
        </div>
    </div>
    <div class="text-center my-4">
        @Html.ActionLink("Edytuj dane klienta", "Edit", new { id = Model.IdCustomer }, new { @class = "btn btn-outline-dark font-weight-bold" })
        @if (Context.User.IsInRole("Admin"))
        {
            @Html.ActionLink("Usuń klienta", "Delete", new { id = Model.IdCustomer }, new { @class = "btn btn-outline-danger font-weight-bold" })
        }
    </div>
    @if (ViewBag.Modal != null)
    {
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            @if (Model.User.LockoutEndDateUtc == null)
                            {
                                <span>Konto zostało odblokowane</span>
                            }
                            else
                            {
                                <span>Konto zostało zablokowane</span>
                            }
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <div class="text-center">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

</section>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("#myModal").modal('show');
    });
</script>